service: sample-app # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-northeast-1

functions:
  infoRead:
    handler: handler.infoRead
    events:
      - http:
          path: info/read
          method: get